settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: server
  path: .
  commands:
    install:
      status: true
      method: go build -o ./realize
    run:
      status: true
      method: ./realize
  watcher:
    extensions:
    - go
    - html
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
